//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enler
    {
        public int enlerID { get; set; }
        public string haftaninOyuncusu { get; set; }
        public string haftaninOrtasahasi { get; set; }
        public string haftaninForveti { get; set; }
        public string haftaninDefansi { get; set; }
        public string haftaninKalecisi { get; set; }
    }
}
