//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maclar
    {
        public int macID { get; set; }
        public int birinciTakimID { get; set; }
        public int ikinciTakimID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public int birinciTakimSkor { get; set; }
        public int ikinciTakimSkor { get; set; }
        public string ad { get; set; }
        public string birinciTakimAdi { get; set; }
        public string ikinciTakimAdi { get; set; }
        public int grupID { get; set; }
    
        public virtual Gruplar Gruplar { get; set; }
    }
}
