//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKyk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mfshalis_Entities : DbContext
    {
        public mfshalis_Entities()
            : base("name=mfshalis_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Enler> Enler { get; set; }
        public virtual DbSet<Gruplar> Gruplar { get; set; }
        public virtual DbSet<Maclar> Maclar { get; set; }
        public virtual DbSet<OynanacakMaclar> OynanacakMaclar { get; set; }
        public virtual DbSet<Oyuncular> Oyuncular { get; set; }
        public virtual DbSet<Takimlar> Takimlar { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
    }
}
