//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OynanacakMaclar
    {
        public int oynanacakmacID { get; set; }
        public string birincitakimismi { get; set; }
        public string ikincitakimismi { get; set; }
        public System.DateTime mactarihi { get; set; }
        public int grupID { get; set; }
    
        public virtual Gruplar Gruplar { get; set; }
    }
}
