//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oyuncular
    {
        public int oyuncuID { get; set; }
        public string ad { get; set; }
        public int golSayisi { get; set; }
        public int asistSayisi { get; set; }
        public int takimID { get; set; }
        public int sariKartSayisi { get; set; }
        public int kirmiziKartSayisi { get; set; }
        public int mesafe { get; set; }
        public int formaNo { get; set; }
    
        public virtual Takimlar Takimlar { get; set; }
    }
}
