//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKyk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takimlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Takimlar()
        {
            this.Oyuncular = new HashSet<Oyuncular>();
        }
    
        public int takimID { get; set; }
        public string ad { get; set; }
        public int toplamPuan { get; set; }
        public int attigiGol { get; set; }
        public int yedigiGol { get; set; }
        public int averaj { get; set; }
        public int galibiyet { get; set; }
        public int maglubiyet { get; set; }
        public int grupID { get; set; }
        public int beraberlik { get; set; }
        public int oynananMac { get; set; }
        public Nullable<int> deneme { get; set; }
        public int aaa { get; set; }
    
        public virtual Gruplar Gruplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oyuncular> Oyuncular { get; set; }
    }
}
